package def.highcharts;
/**
 * Describes the map projection and transformations applied to a portion of a
 * map.
 */
@jsweet.lang.Interface
public abstract class GeoJSONTranslation extends def.js.Object {
    /**
     * The coordinate reference system used to generate this portion of the map.
     */
    public String crs;
    /**
     * Define the portion of the map that this defintion applies to. Defined as
     * a GeoJSON polygon feature object, with `type` and `coordinates`
     * properties.
     */
    @jsweet.lang.Optional
    public Dictionary<?> hitZone;
    /**
     * Property for internal use for maps generated by Highsoft.
     */
    @jsweet.lang.Optional
    public double jsonmarginX;
    /**
     * Property for internal use for maps generated by Highsoft.
     */
    @jsweet.lang.Optional
    public double jsonmarginY;
    /**
     * Property for internal use for maps generated by Highsoft.
     */
    @jsweet.lang.Optional
    public double jsonres;
    /**
     * Specifies clockwise rotation of the coordinates after the projection, but
     * before scaling and panning. Defined in radians, relative to the
     * coordinate system origin.
     */
    @jsweet.lang.Optional
    public double rotation;
    /**
     * The scaling factor applied to the projected coordinates.
     */
    @jsweet.lang.Optional
    public double scale;
    /**
     * Property for internal use for maps generated by Highsoft.
     */
    @jsweet.lang.Optional
    public double xoffset;
    /**
     * X offset of projected coordinates after scaling.
     */
    @jsweet.lang.Optional
    public double xpan;
    /**
     * Property for internal use for maps generated by Highsoft.
     */
    @jsweet.lang.Optional
    public double yoffset;
    /**
     * Y offset of projected coordinates after scaling.
     */
    @jsweet.lang.Optional
    public double ypan;
}

